force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorSkills__c/MentorSkills__c.object-meta.xml
<CustomObject>
    <label>Mentor Skills</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Mentor Skills</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mentor Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MentorSkills__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <label>Average Rating</label>
    <summarizedField>Mentorship__c.Mentor_Skill_Rating__c</summarizedField>
    <summaryForeignKey>Mentorship__c.Mentor_Skills__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MentorSkills__c/fields/MentorId__c.field-meta.xml
<CustomField>
    <fullName>MentorId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MentorId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mentor Skills</relationshipLabel>
    <relationshipName>Mentor_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorSkills__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill3__c</referenceTo>
    <relationshipLabel>Mentor Skills</relationshipLabel>
    <relationshipName>Mentor_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill3__c/Skill3__c.object-meta.xml
<CustomObject>
    <label>Custom Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MentorsBasedOnSkill.cls
public with sharing class MentorsBasedOnSkill {

    public class PotentialMentorsWithSkills {
        PotentialMentorsWithSkills(){
            allSkillNames = new List<String>();
        }

        @AuraEnabled
        public String mentorName;

        @AuraEnabled
        public Id mentorSkillId;

        @AuraEnabled
        public Id mentorId;

        @AuraEnabled
        public String skillId;

        @AuraEnabled
        public String skillName;

        @AuraEnabled
        public Decimal rating;

        @AuraEnabled
        public List<String> allSkillNames;
        
        @AuraEnabled
        public String email;

        @AuraEnabled
        public String location;

        @AuraEnabled
        public String userId;

        @AuraEnabled
        public String dataId;

        @AuraEnabled
        public String menteeName;
    }

    @AuraEnabled (cacheable=true) 
    public static List<PotentialMentorsWithSkills> getMentorsBasedOnSkill(String[] skillId) {
       System.debug('SkillId:'+skillId);

        List<MentorSkills__c> mentorIdWithRequiredSkills = [SELECT Id, MentorId__c , MentorId__r.Name,MentorId__r.PersonEmail, MentorId__r.Location__c, MentorId__r.UserId__c, skill__c , skill__r.name, Average_Rating__c FROM MentorSkills__c WHERE Skill__c  IN :skillId LIMIT 10];

        List<PotentialMentorsWithSkills> potentialMentorsWithSkills = new List<PotentialMentorsWithSkills>();
        for(MentorSkills__c mentoSkills : mentorIdWithRequiredSkills){
            PotentialMentorsWithSkills potentialMentor = new PotentialMentorsWithSkills();
            potentialMentor.mentorId = mentoSkills.MentorId__c;
            potentialMentor.mentorName = mentoSkills.MentorId__r.Name;
            potentialMentor.skillId = mentoSkills.skill__c;
            potentialMentor.skillName = mentoSkills.skill__r.name;
            potentialMentor.rating = mentoSkills.Average_Rating__c;
            potentialMentor.email = mentoSkills.MentorId__r.PersonEmail;
            // potentialMentor.location = [select city from user where id=:mentoSkills.MentorId__r.UserId__c] ;//mentoSkills.MentorId__r.Location__c;
            potentialMentor.userId = mentoSkills.MentorId__r.UserId__c;
            potentialMentor.mentorSkillId = mentoSkills.Id;
            potentialMentor.dataId =  potentialMentor.mentorId + '_'+ potentialMentor.skillId;
            potentialMentor.menteeName = UserInfo.getName();
            List<MentorSkills__c> allMentorSkills = [SELECT  skill__r.name  FROM MentorSkills__c WHERE MentorId__c = :mentoSkills.MentorId__c];
            for(MentorSkills__c skill : allMentorSkills){
                potentialMentor.allSkillNames.add(skill.skill__r.name);
            }
            if(allMentorSkills != null && allMentorSkills.size() > 0 && potentialMentor.mentorName != null){
                potentialMentorsWithSkills.add(potentialMentor);
            }
            System.debug('potentialMentor:'+potentialMentor);
        }
        return potentialMentorsWithSkills;

    }
}