force-app/main/default/objects/Account/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mentorship__c/Mentorship__c.object-meta.xml
<CustomObject>
    <label>Mentorship</label>
    <nameField>
        <label>Mentorship</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mentorship__c/fields/MenteeId__c.field-meta.xml
<CustomField>
    <fullName>MenteeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mentorships (MenteeId)</relationshipLabel>
    <relationshipName>Mentorships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mentorship__c/fields/Mentor_Skills__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Skills__c</fullName>
    <label>Mentor Skills</label>
    <referenceTo>MentorSkills__c</referenceTo>
    <relationshipLabel>Mentorships (Mentor Skills)</relationshipLabel>
    <relationshipName>Mentorships1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mentorship__c/fields/MentorId__c.field-meta.xml
<CustomField>
    <fullName>MentorId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mentorships</relationshipLabel>
    <relationshipName>Mentorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mentorship__c/fields/Program_Id__c.field-meta.xml
<CustomField>
    <fullName>Program_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentorship Program</label>
    <referenceTo>Mentorship_Program__c</referenceTo>
    <relationshipLabel>Mentorships</relationshipLabel>
    <relationshipName>Mentorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mentorship__c/fields/Request_Message__c.field-meta.xml
<CustomField>
    <fullName>Request_Message__c</fullName>
    <label>Request Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mentorship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mentorship_Program__c/Mentorship_Program__c.object-meta.xml
<CustomObject>
    <label>Mentorship Program</label>
    <nameField>
        <label>Mentorship Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MentorshipPrograms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mentorship_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New,InProgress,Completed,Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MentorSkills__c/MentorSkills__c.object-meta.xml
<CustomObject>
    <label>Mentor Skills</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Mentor Skills</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mentor Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MentorSkills__c/fields/MentorId__c.field-meta.xml
<CustomField>
    <fullName>MentorId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MentorId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mentor Skills</relationshipLabel>
    <relationshipName>Mentor_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MentorSkills__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill3__c</referenceTo>
    <relationshipLabel>Mentor Skills</relationshipLabel>
    <relationshipName>Mentor_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill3__c/Skill3__c.object-meta.xml
<CustomObject>
    <label>Custom Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MentorshipHandler.cls
public with sharing class MentorshipHandler {

    public class mentorshipList{
      public mentorShipList(){
          mentorships = new List<mentorship>();
      }
  
      @AuraEnabled
      public List<mentorship> mentorships;
  }
  
  public class mentorship {
      @AuraEnabled
      public Id personId;
  
      @AuraEnabled
      public Id mID;
  
      @AuraEnabled
      public String personName;
  
      @AuraEnabled
      public String status;
  
      @AuraEnabled
      public Date startDate;
  
      @AuraEnabled
      public Date endDate;
  
      @AuraEnabled
      public String skillName;
  
      @AuraEnabled
      public String programName;
  
      @AuraEnabled
      public String mentorshipId;
  
      @AuraEnabled
      public Date lastmodifiedDate;
  
      @AuraEnabled
      public Boolean newMentorshipFlag;

      @AuraEnabled
      public Id menteeUserId;

      @AuraEnabled
      public String menteeEmail;

      @AuraEnabled
      public Id menteeId;
  
  }
      @AuraEnabled(cacheable=true)
      public static mentorshipList findAllMenteeRequests(){
          return getAllMenteeRequestForCurrentUser();
      }
  
      @AuraEnabled
      public static mentorshipList updateDBFormentorship(String mentorshipId,String action,String message){
        try{
          if(!FeatureManagement.checkPermission('Mentorforce_Permission')){
            throw new NoAccessException();
          } 
          Mentorship__c mentorship=new Mentorship__c(Id=mentorshipId);
        if(action.equals('Accept Request')){
          mentorship.status__c='Accepted';
          if( message != null){
            mentorship.Request_Message__c=message;
          }
        }else if(action.equals('Decline')){
          mentorship.status__c='Rejected';
          if( message != null){
            mentorship.Rejection_Reason__c=message;
          }
        }
        update mentorship;
        }catch(Exception e){
          system.debug('Errors:'+ e.getCause());
        }  
        mentorshipList mentorShipListRecs = new mentorshipList();
        mentorShipListRecs=getAllMenteeRequestForCurrentUser();
        return mentorShipListRecs;
      }
  
      public static mentorshipList getAllMenteeRequestForCurrentUser(){
        if(!FeatureManagement.checkPermission('Mentorforce_Permission')){
          throw new NoAccessException();
        } 
        mentorshipList mentorShipListRecs = new mentorshipList();
          List<MentorShip__c> mentorships = new List<MentorShip__c>();
          Id personId = null;
          Id mentorRecordId = [SELECT Id FROM RecordType where Name='Mentor' and SobjectType='Account'].get(0).Id;
          List<Account> personAccounts = [select Id,name from account where userId__c=:UserInfo.getUserId() and recordTypeId=:mentorRecordId];
          
          if(personAccounts != null && personAccounts.size() > 0){
            personId = personAccounts.get(0).Id;
            mentorships = [select Id, lastModifiedDate,menteeid__r.Name, status__c,start_date__c,end_date__c,Mentor_Skills__r.Skill__c,menteeid__r.userid__c, menteeid__r.PersonEmail,menteeid__c,Program_Id__r.Name  from mentorship__c where MentorId__c=:personId LIMIT 5];
          }
          for(Mentorship__c men: mentorships) {
            mentorship mentorshipRec = new mentorship();
            mentorshipRec.personId = personId;
            mentorshipRec.personName = men.menteeid__r.Name;
            mentorshipRec.mID=men.Id;
            if(String.valueOf(men.status__c).equals('New')){
              mentorshipRec.status = 'Received';
              mentorshipRec.newMentorshipFlag=true;
            }else{
              mentorshipRec.status = men.status__c;
              mentorshipRec.newMentorshipFlag=null;
            }
            mentorshipRec.lastModifiedDate=men.lastModifiedDate.date();
            mentorshipRec.startDate = men.start_date__c;
            mentorshipRec.endDate  = men.end_date__c;
            mentorshipRec.programName = men.Program_Id__r.Name;
            mentorshipRec.mentorshipId = men.Id;
            mentorshipRec.menteeEmail = men.menteeid__r.PersonEmail;
            mentorshipRec.menteeUserId = men.menteeid__r.userid__c;
            mentorshipRec.menteeId = men.menteeid__c;
            Id skillId = men.Mentor_Skills__r.Skill__c;
            Skill3__c skill = [SELECT Name FROM Skill3__c WHERE Id =:skillId];
            mentorshipRec.skillName = skill.Name;
            mentorShipListRecs.mentorships.add(mentorshipRec);
        }
          return mentorShipListRecs;
      }
      @AuraEnabled
      public static Boolean createMentorFlag(){
        if(!FeatureManagement.checkPermission('Mentorforce_Permission')){
          throw new NoAccessException();
        } 
        Id mentorRecordId = [SELECT Id FROM RecordType where Name='Mentor' and SobjectType='Account'].get(0).Id;
        List<Account> personAccounts = [select Id,name from account where userId__c=:UserInfo.getUserId() and recordTypeId=:mentorRecordId];
        if(personAccounts == null){
          return true;
        }
        return false;
      }
      @AuraEnabled
      public static Boolean noRequestFlag(){
        if(!FeatureManagement.checkPermission('Mentorforce_Permission')){
          throw new NoAccessException();
        } 
        Id personId = null;
        List<MentorShip__c> mentorships;
        Id mentorRecordId = [SELECT Id FROM RecordType where Name='Mentor' and SobjectType='Account'].get(0).Id;
        List<Account> personAccounts = [select Id,name from account where userId__c=:UserInfo.getUserId() and recordTypeId=:mentorRecordId];
        if(personAccounts != null && personAccounts.size() > 0){
          personId = personAccounts.get(0).Id;
          mentorships = [select Id from mentorship__c where MentorId__c=:personId LIMIT 5];
        }
        if(mentorships != null && mentorships.size() > 0){
          return false;
        }
        return true;
      }
  }